### ISSUE TITLE
Henry doesn't run on my GitHub Pages Repo

### ISSUE THREAD

**Issue by NeodymiumPhish** [kaushikgopal/henry-jekyll#4]
I went through the process of building the whole site locally, then committed/pushed it to my public GH Page and GitHub says `There isn't a GitHub Pages site here.` 

Is there a way to fix this, or will Henry just not work with GH Pages?

**Comment by NeodymiumPhish** [comment]
I've checked the options, and this is what I'm seeing now:

![image](https://user-images.githubusercontent.com/7989828/112376385-63b7f680-8cb2-11eb-848a-a4949f8dbb02.png)

**Comment by NeodymiumPhish** [comment]
OK, I don't have enough content on my site to thoroughly test and ensure nothing is broken, but the 2 issues that prevented GH Pages from building were: 

- needed to import `jekyll-feed` and `jekyll-seo-tag` plugins to `_config` 
- `_initialize` references `code` in line 2, but GH Pages expects the file to be `code.scss`. The included `code` file in the Henry repo is `code.css`, so this fails. Simply renaming to `code.scss` has fixed this problem (again, assuming this doesn't break something unforeseen.

**Comment by kaushikgopal** [comment]
@NeodymiumPhish : 🙏🏽 thanks for the detailed feedback. wrt the 2 issues:

> needed to import jekyll-feed and jekyll-seo-tag plugins to _config

This is interesting. one of the reasons i use firebase hosting vs github pages is the ability to add custom plugins. That being said, Henry doesn't use any fancy plugin and the basic ones like `jekyll-feed ` and `jekyll-seo-tag` can just be included in the theme `config` file so you wouldn't have to add it to your local config. That should address this issue. i'll add that as a fix.

> _initialize references code in line 2, but GH Pages expects the file to be code.scss. The included code file in the Henry repo is code.css, so this fails. Simply renaming to code.scss has fixed this problem (again, assuming this doesn't break something unforeseen.

This should be pretty straightforward. let me address this too.

**Comment by kaushikgopal** [comment]
fwiw, i'm also planning to just remove `jekyll-seo-tag` what it does is pretty simple and i'd probably like to make it easier, so will remove that at some point in the future and bake it into the theme.

**Comment by kaushikgopal** [comment]
When looking at the [jekyll plugin docs](https://jekyllrb.com/docs/plugins/installation/), i noticed this:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/1042037/112392459-a976be00-8cb6-11eb-94a3-8c01289c98d9.png">

Henry uses these plugins currently (it's pulled from [the docker config](https://github.com/kaushikgopal/jekyll-docker-blog-build/blob/master/Gemfile#L9)):

```ruby

group :jekyll_plugins do
    gem "jekyll-feed","~> 0.15"
    gem "jekyll-redirect-from","~> 0.16"
    gem "jekyll-seo-tag","~> 2.7"
    gem "jekyll-sitemap", "~> 1.4"
end
```

GH provides an allowed list of [plugins here](https://pages.github.com/versions/) and all of the plugins Henry uses are currently not blocked.

There are a few ways to solve this issue in retrospect:

1. add them to the base theme `_config` file. risk here is the plugin versions don't match but otherwise, should just work.
2. ask GH pages users to copy the [`Gemfile`](https://github.com/kaushikgopal/jekyll-docker-blog-build/blob/master/Gemfile) from the docker config and be on their way


@NeodymiumPhish : do you have a preference? The easy way to test option `1` btw is just adding this to your `_config` file:

```yml
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
```

**Comment by NeodymiumPhish** [comment]
Copying the Gemfile seems the simplest, in my opinion,  but I'd be fine with either. 

All I added the Plugins was jekyll-feed and jekyll-seo-tag, along with renaming code.css to code.scss and it's running fine (you can take a look at https://neodymiumphi.sh or https://neodymiumphish.github.io

**Comment by NeodymiumPhish** [comment]
If you'd like,  I can try and write up some instructions for GH Pages users and submit a pr.

**Comment by kaushikgopal** [comment]
That would actually be fantastic ! I don’t use GitHub pages so if trust
your instructions better.

Please submit a PR and I’ll be happy to merge.

**Comment by NeodymiumPhish** [comment]
PR submitted!
